<?php

/**
 * @file
 * Adds autocomplete capabilities for Search API searches.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\search_api\Entity\Index;
use Drupal\search_api_autocomplete\AutocompleteFormUtility;
use Drupal\search_api_autocomplete\Entity\Search;

/**
 * Implements hook_theme().
 */
function search_api_autocomplete_theme() {
  $themes['search_api_autocomplete_suggestion'] = [
    'variables' => [
      'keys' => NULL,
      'prefix' => NULL,
      'suggestion_prefix' => '',
      'user_input' => '',
      'suggestion_suffix' => '',
      'results' => NULL,
    ],
  ];

  return $themes;
}

/**
 * Implements hook_entity_operation().
 */
function search_api_autocomplete_entity_operation(EntityInterface $entity) {
  if ($entity->getEntityTypeId() != 'search_api_index') {
    return [];
  }

  $operations = [];
  $operations['autocomplete'] = [
    'title' => t('Autocomplete'),
    'weight' => 30,
    'url' => Url::fromRoute('search_api_autocomplete.admin_overview', ['search_api_index' => $entity->id()]),
  ];
  return $operations;
}

/**
 * Implements hook_form_FORM_ID_alter() for "views_exposed_form".
 *
 * Adds autocompletion to input fields for fulltext keywords on views with
 * exposed filters.
 *
 * @see \Drupal\views\Form\ViewsExposedForm
 * @see \Drupal\search_api_autocomplete\Plugin\search_api_autocomplete\type\Views
 */
function search_api_autocomplete_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $form_state->get('view');
  if (substr($view->storage->get('base_table'), 0, 17) != 'search_api_index_') {
    return;
  }
  $search = Search::load('search_api_views_' . $view->id());
  if (!$search) {
    return;
  }

  if (!$fields = $search->getIndex()->getFulltextFields()) {
    return;
  }
  // Add the "Search: Fulltext search" filter as another text field.
  $fields[] = 'search_api_fulltext';

  \Drupal::moduleHandler()->alter('search_api_autocomplete_views_fulltext_fields', $fields, $search, $view);

  foreach ($view->filter as $filter_name => $filter) {
    $key = $filter->options['expose']['identifier'];
    if (!in_array($filter->realField, $fields)
        || empty($filter->options['expose']['identifier'])
        || !isset($form[$key])) {
      continue;
    }

    $element = &$form[$key];
    // The Views filter for individual fulltext fields uses a nested "value"
    // field for the real input, due to Views internals.
    if (!empty($element['value'])) {
      $element = &$element['value'];
    }
    if ($element['#type'] == 'textfield') {
      if ($filter->realField == 'search_api_fulltext') {
        $autocomplete_fields = $filter->options['fields'];
      }
      else {
        $autocomplete_fields = [$filter->realField];
      }
      AutocompleteFormUtility::alterElement($element, $search, $autocomplete_fields);
    }
    unset($element);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for "search_api_page_block_form".
 *
 * Adds autocompletion to the keywords field on search pages, if enabled by the
 * user.
 *
 * @see \Drupal\search_api_page\Form\SearchApiPageBlockForm
 * @see \Drupal\search_api_autocomplete\Plugin\search_api_autocomplete\type\Page
 */
function search_api_autocomplete_form_search_api_page_block_form_alter(array &$form, FormStateInterface $form_state) {
  $id = 'search_api_page_' . $form_state->getBuildInfo()['args'][0]['search_api_page'];
  $search = Search::load($id);

  if ($search && $search->status()) {
    AutocompleteFormUtility::alterElement($form['keys'], $search);
  }
}
